#+TITLE: Dealing with Disrespectful Behavior
#+AUTHOR: Russell Helmstedter
#+DATE: <2023-02-28 Tue>
#+OPTIONS: \n:t
#+LATEX_HEADER: \makeatletter \@ifpackageloaded{geometry}{\geometry{margin=1in}}{\usepackage[margin=1in]{geometry}} \makeatother\hypersetup{colorlinks, allcolors=., urlcolor=blue,}\bigskip
* The Problem
** Disrespectful Behavior
There is a consensus that disrespectful behavior exhibited by students has reached an unacceptable level. We are defining disrespect as deliberate action such as walking away, defying, or talking back to a reasonable request from any adult on campus. While we agree that while there are other important issues, this is the principle non-negotiable issue we are facing. Teachers have committed to focusing on this one issue above all others. We need to reset the current narrative by coming out in full force and presenting a united front. The solution to this problem is twofold:
1) Educate
2) Enforce Consequences
* Solutions
** Educate
We are educators and this is what we do best. We need to teach students what constitutes disrespectful behavior and that will not be allowed at this school. Teachers have committed to creating slides that show clear examples of disrespect. These slides are to be pushed out in homeroom. When appropriate, all staff members need to identify disrespectful behavior and explain to students why it is disrespectful.
** Consequences
Teachers have agreed that any student who exhibits disrespect to any adult on campus will serve a lunch detention. There will be an initial 2-week implementation where teachers will volunteer to host detention in their classrooms. There will be no clubs during these two weeks since teachers will be hosting detention. Lunch detentions will consist of no more than 5 students per room. While serving a lunch detention, student use of electronic devices is prohibited. Furthermore, students are to complete a /staff apology letter/. This letter will provide students an opportunity to reflect on their behavior. If the letter is not completed, students will be assigned additional detentions until the completion of the letter.
** Scope
In order for this campaign to be successful, it is crucial that our focus remains narrow and all staff members work towards de-escalation of situations when possible. Lunch detentions may only be assigned for disrespectful behavior. Behavior outside the scope of disrespect includes, but is not limited to: dress code violations, cell phone use, tardies, missing assignments, or academic infractions. Behavior outside the scope of disrespect must be addressed in another fashion.

If teachers need further support with broader classroom management, Mike Robinson has offered support for implementing CHAMPS.
** Logistics [1/5]
**** STRT Creation of Slides for Homeroom :@Wulff:
DEADLINE: <2023-02-28 Tue>
\n
Due:  <2023-02-28 Tue>
*Status*: Currently in draft form: [[https://docs.google.com/presentation/d/1KKa5UEtjeGV4UMOOm35VP2P7YFTUVjxKv-Us0XIVoMk/edit?usp=sharing][slides for homeroom]].
**** STRT Creation of Google Sheet :@Durkee:
DEADLINE: <2023-02-28 Tue>
\n
*Due*: <2023-02-28 Tue>
*Status*: Currently in draft form: [[https://docs.google.com/spreadsheets/d/12TRL6GPD7My0B4FP1R4O19bCQTj2PNMqy49vHuAmTLw/edit?usp=sharing][google sheet]]. Email was sent to staff and several teachers volunteered. Durkee has placed teachers in the sheet.
**** STRT Creation of Staff Apology Letter :@Willis:@StClare:
DEADLINE: <2023-03-01 Wed>
\n
*Due*: <2023-03-01 Wed>
*Status*: Spoke with St. Clare <2023-02-28 Tue>. Draft has been reviewed by Lukins, Willis, Helmstedter.
**** STRT Create Generic Parent Email :@Pipkin:
DEADLINE: <2023-02-28 Tue>
\n
*Due*: <2023-02-28 Tue>
*Status*: Spoke with Pipkin, draft sent to Durkee <2023-02-28 Tue>.
**** DONE Assign a /Monitor Teacher/ :@Helmstedter:
DEADLINE: <2023-03-03 Fri>
\n
*Due*: <2023-03-03 Fri>
*Status*: Email was sent to staff asking if their were volunteers for the monitor teacher. No teacher volunteered. Helmstedter is assigned to be the monitor teacher for the initial 2 week period. Will coordinate with admin, campus supervisors, and detention teachers.
** Admin Support [0/3]
*Status*: +Helmstedter and Davidson will meet with Admin <2023-02-28 Tue> to discuss the following tasks.+ Admin had to deal with a situation after school. Meeting is now scheduled <2023-03-02 Thu 07:45>.
**** TODO Determine Consequences for No Shows :@Admin:
DEADLINE: <2023-03-03 Fri>
\n
*Due*: <2023-03-03 Fri>
**** TODO Determine Student Notification Procedure :@Admin:
DEADLINE: <2023-03-03 Fri>
\n
*Due*: <2023-03-03 Fri>
**** TODO Draft Parent Square Notification :@Admin:
DEADLINE: <2023-03-03 Fri>
\n
*Due*: <2023-03-03 Fri>
** Items TBD [0/1]
**** TODO Determine if Parent Contact is Required :@Helmstedter:
DEADLINE: <2023-03-03 Fri>
\n
*Due*: <2023-03-03 Fri>
* Timeline for Initial 2 week Implementation
** Create Necessary Documents
DEADLINE: <2023-03-03 Fri> SCHEDULED: <2023-02-27 Mon>
The week of Mon Feb 27, 2023.

There are 4 major documents that need to be created
+ [[https://docs.google.com/presentation/d/1KKa5UEtjeGV4UMOOm35VP2P7YFTUVjxKv-Us0XIVoMk/edit?usp=sharing][Homeroom Slides (Draft)]]
+ [[https://docs.google.com/spreadsheets/d/12TRL6GPD7My0B4FP1R4O19bCQTj2PNMqy49vHuAmTLw/edit?usp=sharing][Google Sheet (Draft)]]
+ Staff Apology Letter
+ Generic Email for Parents

** Begin Education Campaign
DEADLINE: <2023-03-10 Fri> SCHEDULED: <2023-03-06 Mon>
The week of Mon Mar 6, 2023.
** First week of lunch detention
DEADLINE: <2023-03-17 Fri> SCHEDULED: <2023-03-13 Mon>
The week of Mon Mar 13, 2023.
** Second week of lunch detention
DEADLINE: <2023-03-24 Fri> SCHEDULED: <2023-03-20 Mon>
The week of Mon Mar 20, 2023.
** Scaled Down Detention
DEADLINE: <2023-03-31 Fri> SCHEDULED: <2023-03-27 Mon>
The week of Mon Mar 27, 2023.
* Future Issues
After the initial two week period, we can scale back the number of teachers involved in hosting the detentions. This will involve a rotation of teachers.
** Logistics [0/3]
**** TODO Construct a Rotating Calendar :@Admin:
DEADLINE: <2023-03-24 Fri>
\n
*Due*: <2023-03-24 Fri>
**** TODO Procedure for Getting People Paid :@Admin:
DEADLINE: <2023-03-24 Fri>
\n
*Due*: <2023-03-24 Fri>
**** TODO Procedure for Tracking Repeat Students :@Admin:
DEADLINE: <2023-03-24 Fri>
\n
*Due*: <2023-03-24 Fri>
