#+title: Operations Agenda For Leadership
#+date: <2023-03-07 Tue>
#+author: Russell Helmstedter
#+LATEX_HEADER: \makeatletter \@ifpackageloaded{geometry}{\geometry{margin=1in}}{\usepackage[margin=1in]{geometry}} \makeatother\hypersetup{colorlinks, allcolors=., urlcolor=blue,}\bigskip
#+ATTR_LATEX: :environment quotation
* Review Documents
+ [[https://docs.google.com/spreadsheets/d/12TRL6GPD7My0B4FP1R4O19bCQTj2PNMqy49vHuAmTLw/edit?usp=sharing][Google Sheet]]
+ [[https://docs.google.com/document/d/1GiSqw4xslS1L3ioGGRFosYYuLP2ziROc/edit?usp=sharing&ouid=103300073545602807799&rtpof=true&sd=true][Staff Apology Letter]]
+ [[https://docs.google.com/document/d/18eMGA8ScMb8S8B4G99kOatsZstaJ_c0fWdk8wJq6EZo/edit?usp=sharing][Generic Email for Parents]]
* Assigning Detentions
In order for this campaign to be successful, it is crucial that our focus remains narrow and all staff members work towards de-escalation of situations when possible. Lunch detentions may only be assigned for disrespectful behavior. Behavior outside the scope of disrespect includes, but is not limited to: dress code violations, cell phone use, tardies, missing assignments, or academic infractions. Behavior outside the scope of disrespect must be addressed in another fashion.

Any staff member on campus may assign detentions for disrespectful behavior. When possible, teachers should assign detentions to themselves first. When the teacher is full, they may assign students to any classroom with open spots.
** Assignor Responsibilities
1. Fill out paper slip detention slip. Give the pink copy to the student.
2. Fill in the student name on the spreadsheet.
3. Send the white copy of the detention slip to the office.
** Questions
What about students on a 4 period day?
* Hosting Detentions
** Meal Service
Cafeteria manager will make lunches for students serving detention. These will be delivered to the host teachers classroom at the end of the second block.
** Student Guidelines
+ No use of electronic devices, including Chromebooks.
+ Write the staff apology letter.
+ Follow directions of the host teacher.
** Host Guidelines
At your discretion, students may be assigned an additional day for the following reasons:
+ Failing to complete the letter.
+ Disrespectful behavior during the detention.
** Students Who Don't Show Up
There will be a Friday after school detention in C-3. We can do this option as long as we notify parents, provide transportation, and offer a Saturday option for any student who wishes to not stay after school.
** Questions
What do we do about escalation of behavior during detention?
