#+TITLE: Site Rep Council Meeting
#+AUTHOR: Russell Helmstedter
#+DATE: <2022-12-12 Mon>

* Negotiations as of <2022-12-12>
Nothing is written on paper. VUEA and the district only reached a verbal agreement. They will meet again on Tuesday December 13 to work out the details.
** Health Care
*** The Cap
Switching to CSEBO costs less which saves the district money compared to Gold Coast ($21 million as opposed to $25 million). This savings does not go into effect until July 2023. There is a plan to put in trigger language to re-negotiate the existence of a cap once healthcare costs once again reaches 90% the current level ($23 million).
*** Switching to CSEBO
Gold Coast was negotiated until July 2023. We will make the switch to CSEBO on July 1, 2023. This results in open enrollment around then. Then there will be most likely a second open enrollment period in the winter because CSEBO (and Gold Coast) run terms of January to December, even though the school year Starts in August.
*** Plans
CSEBO will create a plan that matches the current offerings for the PPO. There is also a match for Kaiser's offering as well.
*** Cash in-lieu of Benefits
Looking at $5,000 annually paid out monthly. This would be the highest in the county. Other districts have maxed out at $3,000. This is prorated for part-time employees.
*** Retirement Questions
For questions regarding retirement plans, like COBRA, members should reach out to Jodie Argueta.
** Salary
10% on-schedule raise with a 2% bonus this year only. If the agreement is ratified by members, checks should be sent out sometime between Jan 15 and Feb 15.
** Passthrough in the future
Dan would like to include passthrough language in negotiated deals. For example, if the COLA is 8.32% and the passthrough language is at 80%, then the lowest offer should be 80% of 8.32% = 6.66%. This would prevent offers such as the 1.5% early on from the district. But Dan worries that it could also prevent us for getting a max deal. Difficult to organize around a 1.66% gap.

* Organizing Costs
Currently up to $32,000 approximately. Things like signs/Billboards/Food are covered at 2/3 by CTA. Things like t-shirts are not covered.

* CTA Update
Arleigh Kidd, who was in some of the negotiations shared that the first budget of the state will come out around January 10. Estimated cost of living adjustment from the state: 8.32%

* State Budget
The state can give a budget on July 1 for schools, but has 60 days to take it back. This means the district doesn't know for sure how they are being funded until 60 days post July 1.

* Q & A

** Are admin in the same health care plans as union members? For example, if we were to negotiate a cap in the future, would the cap apply to them as well? Do they have access to the cash-in-lieu as well? Things like that.
YEP, they are.  And the cap would affect them as well and also cash-in-lieu.

** Is there still a "me too" clause in the contract where if we get a raise, admin also gets a raise?
ARGH!  Sorry, mini-rant here.  There is no ‘me too’ clause in our contract (nor VESPAs) nor in the admin contract.  If there was one in the admin contract then we could do nothing about it.  It is the board policy that whatever raise comes to the labor units also goes to the admin and confidential staff.

** Some members expressed that it is not fair that admin recently got a raise (when we didn't), and now they might get another one with the (yet to be) ratified contract.
I agree with those members!

** As an aside, it is my current understanding that technically speaking, admin did not receive a raise, but did increase the number of contract days. Is that correct?
They did get a raise; I don’t know if they increased their days though.


* Concerns to raise

Justify pay raise with 1 AP moving forward? Under 600 results in 1.5 APs with one principal.

Master schedule concerns at the district level. Knowing schedules prior to the day before.

preferred schedule survey? last year was never sent out.
