#+TITLE: Rep Council Meeting
#+AUTHOR: Russell Helmstedter
#+DATE: <2023-01-23 Mon>

* Treasury 
  Linda Bergfeld is taking over the remaining term for the treasury. She wants to move the funds into CD accounts to earn more interest on the money.
* January Proposed Budget
  The state is facing a deficit. They cut a funding source that was originally slated to
  pay down Cal PRS and STRS. The proposed increase for next is 8.19% (original thoughts
  was approximately 8.3%). This is likely to decrease however.
* Negotiations for 2023-2024
** Sunshining Articles
  Only allowed to open 2 articles each year. This year the district has agreed to jointly open
  article 31 (relating to special ed) so that it doesn't count against the two articles.
  These are up for discussion in August. It is crucial to fill out the survey sent by Dan.
** Passthrough
   Dan is interested in indexing negotiations to COLA. He would like 80% of COLA to be the
   starting point for negotiations. Benefits: avoid low ball offers. Cons: Limits
   flexibility for the district; puts a glass ceiling on potential raises.
* Elections
  Sarah McLaughlin is currently an elementary director but running for president. This
  means if she becomes president that would open her director position. There was a motion
  to allow the choice of two people for elementary director. The second vote getting would
  take her place.
* Healthcare Transition
** 2024 Transition Dates
  Gold Coast coverage expires June 30 2024. CSEBO coverage starts July 1 2024. Dan's
  recommendation is to avoid (if possible) care during that transition. For example,
  getting surgery on June 29, and then starting physical therapy on July 2. This could
  result in you getting billed because the doctor would try to bill Gold Coast in July and
  they will have no money. You will have to work with the district to transition to CSEBO
  which means the district will have your medical information.
** Doctor Choice
   Under Gold Coast, individuals were able to negotiate a doctor outside of the network.
   This would have to be negotiated again with CSEBO—with no guarantee.
** Plans
   Dental and vision plans are better under CSEBO. There is a loyalty clause in the dental
   plan. The more often you go, the more they cover. There is also the option to buy into
   better coverage for vision where you could get both glasses and contacts instead of
   either or.
* Union Finances
** Increase in Dues
  There hasn't been an increase in union dues for a long time. Rent and operating costs
  have risen. There is a proposed increase of $2 per month to a monthly total of $25.
  There are 679 members paying in for 10 months. This yields: 679 * $2 * 10 = $13,580
  increase in funding.
** President Stipend
   Dan wants to raise the stipend from $275 to $300 per month for gas and cell phone.
   This would only go into effect after he is no longer in the postion.
** Support Position
   Dan wants to offer a 10% raise for the support staff position held by Anne Campbell.
